language: node_js
os:
  - linux
node_js:
  - 8
addons:
  chrome: stable
sudo: required
services:
  - xvfb
before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
install:
  - npm install -g electron electron-builder wait-on typescript nyc codecov tslint
  - npm install typescript@3.1.6 -g --save-exact
  - npm set progress=false
  - npm install
script:
  - ng lint
  - ng test --code-coverage
  - codecov
  - npm run build:prod
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then npm run electron:linux ; fi
notifications:
  slack:
    secure: nwTZl+YkUp07ZCBaQNF0ierhCdRsmJmV4rcqpHhAzf+wbTxZbkT5NFp3vmgQiF9Lgvt7j+s07079Dmzjrd8UePs6UEYJSTC7yRjkdNDzD5+vLLf3sryX5L8ppK3KyDtMEYRqRkvIehRGK0kZ2fZmy1YGodB+n0BCVhp+FwIkIeXqUw9i1JxDBILqnUrakE4flK+rwDQBe3Aij78nF8nYsOrXAN2fXshtmJhgXX0WKYn84X/NzZMtW3MolhyxF0FpmZmaao2R3C1UsIIN5ACjWtfz5TT+Sx0wIL63U1o52fJT/sJM9re01wVtMuqooQiK0bhPwaC6myovi/Q2XyWPCyOghvo2MVjaWf+NNoW4jgJCOIFs6rzrCZSkg7WQaysYFmtWqKXuOIkXMNGdKlEy+n4FKiY6ZKV2688SZejIz/KI16dYZwvkiMPK+heO0FtRoakpYEZ7uvSee2g3V40V3uedTHnQAkVQKC01b795mUcwbi5rF93HFyU76fhM69nT7V/266kFGGHgIvQot9YihEytnlDIpJMpgpznSCk8vqDCUXdvhs5gfzhStFt0LcSIZAGx2yPUNlvUdoiyR4rbMSl5A8vc8pndv+RgvrpIFoZPjiEVx7jzn2x5xg6SX6OWev2S9tRoAOg8zAW40WyOgEMAozvOFDiw4tvg6CWoWrQ=
