language: node_js
os:
  - linux
  - osx
  - windows
node_js:
  - 8
sudo: required
addons:
  chrome: stable
before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - 'if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start ; fi'
install:
  - npm install -g electron electron-builder wait-on typescript nyc codecov
  - npm install typescript@3.1.6 -g --save-exact
  - npm set progress=false
  - npm install
script:
  - ng lint
  - ng test --watch=false --code-coverage
  - codecov
  - npm run build:prod
  - 'if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then npm run electron:linux ; fi'
  - 'if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then npm run electron:windows ; fi'
  - 'if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm run electron:mac ; fi'
