language: node_js
node_js:
  - 8
sudo: required
addons:
  chrome: stable
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - npm install -g electron electron-builder wait-on typescript nyc codecov
  - npm install typescript@3.1.6 -g --save-exact
  - npm set progress=false
  - npm install
script:
  - ng lint
  - ng test --watch=false --code-coverage
  - codecov
  - ng build
  - electron-builder build --windows
